namespace Server.Item.Enchantment
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class Enchantments
	{
	public 	static 	readonly IEnchantment AquaAffinity = EnchantmentImpl.REGISTRY.Get("minecraft:aqua_affinity");

	public 	static 	readonly IEnchantment Multishot = EnchantmentImpl.REGISTRY.Get("minecraft:multishot");

	public 	static 	readonly IEnchantment Piercing = EnchantmentImpl.REGISTRY.Get("minecraft:piercing");

	public 	static 	readonly IEnchantment Power = EnchantmentImpl.REGISTRY.Get("minecraft:power");

	public 	static 	readonly IEnchantment ProjectileProtection = EnchantmentImpl.REGISTRY.Get("minecraft:projectile_protection");

	public 	static 	readonly IEnchantment Protection = EnchantmentImpl.REGISTRY.Get("minecraft:protection");

	public 	static 	readonly IEnchantment Punch = EnchantmentImpl.REGISTRY.Get("minecraft:punch");

	public 	static 	readonly IEnchantment QuickCharge = EnchantmentImpl.REGISTRY.Get("minecraft:quick_charge");

	public 	static 	readonly IEnchantment Respiration = EnchantmentImpl.REGISTRY.Get("minecraft:respiration");

	public 	static 	readonly IEnchantment Riptide = EnchantmentImpl.REGISTRY.Get("minecraft:riptide");

	public 	static 	readonly IEnchantment Sharpness = EnchantmentImpl.REGISTRY.Get("minecraft:sharpness");

	public 	static 	readonly IEnchantment SilkTouch = EnchantmentImpl.REGISTRY.Get("minecraft:silk_touch");

	public 	static 	readonly IEnchantment Smite = EnchantmentImpl.REGISTRY.Get("minecraft:smite");

	public 	static 	readonly IEnchantment SoulSpeed = EnchantmentImpl.REGISTRY.Get("minecraft:soul_speed");

	public 	static 	readonly IEnchantment SweepingEdge = EnchantmentImpl.REGISTRY.Get("minecraft:sweeping_edge");

	public 	static 	readonly IEnchantment SwiftSneak = EnchantmentImpl.REGISTRY.Get("minecraft:swift_sneak");

	public 	static 	readonly IEnchantment Thorns = EnchantmentImpl.REGISTRY.Get("minecraft:thorns");

	public 	static 	readonly IEnchantment Unbreaking = EnchantmentImpl.REGISTRY.Get("minecraft:unbreaking");

	public 	static 	readonly IEnchantment VanishingCurse = EnchantmentImpl.REGISTRY.Get("minecraft:vanishing_curse");

	public 	static 	readonly IEnchantment WindBurst = EnchantmentImpl.REGISTRY.Get("minecraft:wind_burst");

	public 	static 	readonly IEnchantment Mending = EnchantmentImpl.REGISTRY.Get("minecraft:mending");

	public 	static 	readonly IEnchantment Lure = EnchantmentImpl.REGISTRY.Get("minecraft:lure");

	public 	static 	readonly IEnchantment LuckOfTheSea = EnchantmentImpl.REGISTRY.Get("minecraft:luck_of_the_sea");

	public 	static 	readonly IEnchantment Channeling = EnchantmentImpl.REGISTRY.Get("minecraft:channeling");

	public 	static 	readonly IEnchantment FireProtection = EnchantmentImpl.REGISTRY.Get("minecraft:fire_protection");

	public 	static 	readonly IEnchantment FrostWalker = EnchantmentImpl.REGISTRY.Get("minecraft:frost_walker");

	public 	static 	readonly IEnchantment Impaling = EnchantmentImpl.REGISTRY.Get("minecraft:impaling");

	public 	static 	readonly IEnchantment Infinity = EnchantmentImpl.REGISTRY.Get("minecraft:infinity");

	public 	static 	readonly IEnchantment Knockback = EnchantmentImpl.REGISTRY.Get("minecraft:knockback");

	public 	static 	readonly IEnchantment Looting = EnchantmentImpl.REGISTRY.Get("minecraft:looting");

	public 	static 	readonly IEnchantment Loyalty = EnchantmentImpl.REGISTRY.Get("minecraft:loyalty");

	public 	static 	readonly IEnchantment Fortune = EnchantmentImpl.REGISTRY.Get("minecraft:fortune");

	public 	static 	readonly IEnchantment Flame = EnchantmentImpl.REGISTRY.Get("minecraft:flame");

	public 	static 	readonly IEnchantment FireAspect = EnchantmentImpl.REGISTRY.Get("minecraft:fire_aspect");

	public 	static 	readonly IEnchantment Density = EnchantmentImpl.REGISTRY.Get("minecraft:density");

	public 	static 	readonly IEnchantment FeatherFalling = EnchantmentImpl.REGISTRY.Get("minecraft:feather_falling");

	public 	static 	readonly IEnchantment Breach = EnchantmentImpl.REGISTRY.Get("minecraft:breach");

	public 	static 	readonly IEnchantment Efficiency = EnchantmentImpl.REGISTRY.Get("minecraft:efficiency");

	public 	static 	readonly IEnchantment DepthStrider = EnchantmentImpl.REGISTRY.Get("minecraft:depth_strider");

	public 	static 	readonly IEnchantment BaneOfArthropods = EnchantmentImpl.REGISTRY.Get("minecraft:bane_of_arthropods");

	public 	static 	readonly IEnchantment BlastProtection = EnchantmentImpl.REGISTRY.Get("minecraft:blast_protection");

	public 	static 	readonly IEnchantment BindingCurse = EnchantmentImpl.REGISTRY.Get("minecraft:binding_curse");

	}
}
