namespace Server.Item.Armor
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class TrimMaterials
	{
	public 	static 	readonly ITrimMaterial Lapis = TrimMaterialImpl.REGISTRY.Get("minecraft:lapis");

	public 	static 	readonly ITrimMaterial Iron = TrimMaterialImpl.REGISTRY.Get("minecraft:iron");

	public 	static 	readonly ITrimMaterial Diamond = TrimMaterialImpl.REGISTRY.Get("minecraft:diamond");

	public 	static 	readonly ITrimMaterial Amethyst = TrimMaterialImpl.REGISTRY.Get("minecraft:amethyst");

	public 	static 	readonly ITrimMaterial Copper = TrimMaterialImpl.REGISTRY.Get("minecraft:copper");

	public 	static 	readonly ITrimMaterial Quartz = TrimMaterialImpl.REGISTRY.Get("minecraft:quartz");

	public 	static 	readonly ITrimMaterial Emerald = TrimMaterialImpl.REGISTRY.Get("minecraft:emerald");

	public 	static 	readonly ITrimMaterial Redstone = TrimMaterialImpl.REGISTRY.Get("minecraft:redstone");

	public 	static 	readonly ITrimMaterial Gold = TrimMaterialImpl.REGISTRY.Get("minecraft:gold");

	public 	static 	readonly ITrimMaterial Netherite = TrimMaterialImpl.REGISTRY.Get("minecraft:netherite");

	}
}
