namespace Server.Item.Armor
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class TrimMaterials
	{
	public 	static 	readonly ITrimMaterial LAPIS = TrimMaterialImpl.REGISTRY.Get("minecraft:lapis");

	public 	static 	readonly ITrimMaterial IRON = TrimMaterialImpl.REGISTRY.Get("minecraft:iron");

	public 	static 	readonly ITrimMaterial DIAMOND = TrimMaterialImpl.REGISTRY.Get("minecraft:diamond");

	public 	static 	readonly ITrimMaterial AMETHYST = TrimMaterialImpl.REGISTRY.Get("minecraft:amethyst");

	public 	static 	readonly ITrimMaterial COPPER = TrimMaterialImpl.REGISTRY.Get("minecraft:copper");

	public 	static 	readonly ITrimMaterial QUARTZ = TrimMaterialImpl.REGISTRY.Get("minecraft:quartz");

	public 	static 	readonly ITrimMaterial EMERALD = TrimMaterialImpl.REGISTRY.Get("minecraft:emerald");

	public 	static 	readonly ITrimMaterial REDSTONE = TrimMaterialImpl.REGISTRY.Get("minecraft:redstone");

	public 	static 	readonly ITrimMaterial GOLD = TrimMaterialImpl.REGISTRY.Get("minecraft:gold");

	public 	static 	readonly ITrimMaterial NETHERITE = TrimMaterialImpl.REGISTRY.Get("minecraft:netherite");

	}
}
