namespace Server
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class MinecraftConstants
	{
	public 	static 	readonly string VERSION_NAME = "1.21";

	public 	static 	readonly int PROTOCOL_VERSION = 767;

	public 	static 	readonly int WORLD_FORMAT_VERSION = 3953;

	public 	static 	readonly int RESOURCE_PACK_VERSION = 34;

	public 	static 	readonly int DATA_PACK_VERSION = 48;

	}
}
