<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
      <PackageReference Include="DotNetty.Codecs" Version="0.7.6" />
      <PackageReference Include="DotNetty.Common" Version="0.7.6" />
      <PackageReference Include="DotNetty.Handlers" Version="0.7.6" />
      <PackageReference Include="DotNetty.Transport" Version="0.7.6" />
      <PackageReference Include="slf4net" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\attributes.json" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\attributes.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\items.json" />
      <EmbeddedResource Include="Resources\items.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\blocks.json" />
      <EmbeddedResource Include="Resources\blocks.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\constants.json" />
      <EmbeddedResource Include="Resources\constants.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\trim_materials.json" />
      <EmbeddedResource Include="Resources\trim_materials.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\custom_statistics.json" />
      <EmbeddedResource Include="Resources\custom_statistics.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Component\" />
    </ItemGroup>

</Project>