<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetty.Buffers" Version="0.7.6" />
    <PackageReference Include="DotNetty.Codecs" Version="0.7.6" />
    <PackageReference Include="DotNetty.Codecs.Mqtt" Version="0.7.6" />
    <PackageReference Include="DotNetty.Common" Version="0.7.6" />
    <PackageReference Include="DotNetty.Handlers" Version="0.7.6" />
    <PackageReference Include="DotNetty.Transport" Version="0.7.6" />
    <PackageReference Include="Joveler.Compression.ZLib" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Network\Packet\Type\Configuration\Client\" />
    <Folder Include="Network\Packet\Type\Configuration\Server\" />
    <Folder Include="Network\Packet\Type\Play\Client\" />
    <Folder Include="Network\Packet\Type\Play\Server\" />
  </ItemGroup>

</Project>
