namespace Server.Attribute
{
	// This file was autogenerated by a script. Do not modify this file manually.
	class Attributes
	{
	public 	static 	readonly IAttribute GENERIC_ARMOR = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_ARMOR_TOUGHNESS = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_ATTACK_DAMAGE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_ATTACK_KNOCKBACK = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_ATTACK_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_BLOCK_BREAK_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_BLOCK_INTERACTION_RANGE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_BURNING_TIME = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_EXPLOSION_KNOCKBACK_RESISTANCE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_ENTITY_INTERACTION_RANGE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_FALL_DAMAGE_MULTIPLIER = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_FLYING_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_FOLLOW_RANGE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_GRAVITY = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_JUMP_STRENGTH = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_KNOCKBACK_RESISTANCE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_LUCK = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_MAX_ABSORPTION = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_MAX_HEALTH = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_MINING_EFFICIENCY = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_MOVEMENT_EFFICIENCY = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_MOVEMENT_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_OXYGEN_BONUS = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_SAFE_FALL_DISTANCE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_SCALE = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_SNEAKING_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute ZOMBIE_SPAWN_REINFORCEMENTS = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_STEP_HEIGHT = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_SUBMERGED_MINING_SPEED = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute PLAYER_SWEEPING_DAMAGE_RATIO = AttributeImpl.REGISTRY.Get("{key}");

	public 	static 	readonly IAttribute GENERIC_WATER_MOVEMENT_EFFICIENCY = AttributeImpl.REGISTRY.Get("{key}");

	}
}
