namespace Server.Attribute
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class Attributes
	{
	public 	static 	readonly IAttribute GENERIC_ARMOR = AttributeImpl.REGISTRY.Get("minecraft:generic.armor");

	public 	static 	readonly IAttribute GENERIC_ARMOR_TOUGHNESS = AttributeImpl.REGISTRY.Get("minecraft:generic.armor_toughness");

	public 	static 	readonly IAttribute GENERIC_ATTACK_DAMAGE = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_damage");

	public 	static 	readonly IAttribute GENERIC_ATTACK_KNOCKBACK = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_knockback");

	public 	static 	readonly IAttribute GENERIC_ATTACK_SPEED = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_speed");

	public 	static 	readonly IAttribute PLAYER_BLOCK_BREAK_SPEED = AttributeImpl.REGISTRY.Get("minecraft:player.block_break_speed");

	public 	static 	readonly IAttribute PLAYER_BLOCK_INTERACTION_RANGE = AttributeImpl.REGISTRY.Get("minecraft:player.block_interaction_range");

	public 	static 	readonly IAttribute GENERIC_BURNING_TIME = AttributeImpl.REGISTRY.Get("minecraft:generic.burning_time");

	public 	static 	readonly IAttribute GENERIC_EXPLOSION_KNOCKBACK_RESISTANCE = AttributeImpl.REGISTRY.Get("minecraft:generic.explosion_knockback_resistance");

	public 	static 	readonly IAttribute PLAYER_ENTITY_INTERACTION_RANGE = AttributeImpl.REGISTRY.Get("minecraft:player.entity_interaction_range");

	public 	static 	readonly IAttribute GENERIC_FALL_DAMAGE_MULTIPLIER = AttributeImpl.REGISTRY.Get("minecraft:generic.fall_damage_multiplier");

	public 	static 	readonly IAttribute GENERIC_FLYING_SPEED = AttributeImpl.REGISTRY.Get("minecraft:generic.flying_speed");

	public 	static 	readonly IAttribute GENERIC_FOLLOW_RANGE = AttributeImpl.REGISTRY.Get("minecraft:generic.follow_range");

	public 	static 	readonly IAttribute GENERIC_GRAVITY = AttributeImpl.REGISTRY.Get("minecraft:generic.gravity");

	public 	static 	readonly IAttribute GENERIC_JUMP_STRENGTH = AttributeImpl.REGISTRY.Get("minecraft:generic.jump_strength");

	public 	static 	readonly IAttribute GENERIC_KNOCKBACK_RESISTANCE = AttributeImpl.REGISTRY.Get("minecraft:generic.knockback_resistance");

	public 	static 	readonly IAttribute GENERIC_LUCK = AttributeImpl.REGISTRY.Get("minecraft:generic.luck");

	public 	static 	readonly IAttribute GENERIC_MAX_ABSORPTION = AttributeImpl.REGISTRY.Get("minecraft:generic.max_absorption");

	public 	static 	readonly IAttribute GENERIC_MAX_HEALTH = AttributeImpl.REGISTRY.Get("minecraft:generic.max_health");

	public 	static 	readonly IAttribute PLAYER_MINING_EFFICIENCY = AttributeImpl.REGISTRY.Get("minecraft:player.mining_efficiency");

	public 	static 	readonly IAttribute GENERIC_MOVEMENT_EFFICIENCY = AttributeImpl.REGISTRY.Get("minecraft:generic.movement_efficiency");

	public 	static 	readonly IAttribute GENERIC_MOVEMENT_SPEED = AttributeImpl.REGISTRY.Get("minecraft:generic.movement_speed");

	public 	static 	readonly IAttribute GENERIC_OXYGEN_BONUS = AttributeImpl.REGISTRY.Get("minecraft:generic.oxygen_bonus");

	public 	static 	readonly IAttribute GENERIC_SAFE_FALL_DISTANCE = AttributeImpl.REGISTRY.Get("minecraft:generic.safe_fall_distance");

	public 	static 	readonly IAttribute GENERIC_SCALE = AttributeImpl.REGISTRY.Get("minecraft:generic.scale");

	public 	static 	readonly IAttribute PLAYER_SNEAKING_SPEED = AttributeImpl.REGISTRY.Get("minecraft:player.sneaking_speed");

	public 	static 	readonly IAttribute ZOMBIE_SPAWN_REINFORCEMENTS = AttributeImpl.REGISTRY.Get("minecraft:zombie.spawn_reinforcements");

	public 	static 	readonly IAttribute GENERIC_STEP_HEIGHT = AttributeImpl.REGISTRY.Get("minecraft:generic.step_height");

	public 	static 	readonly IAttribute PLAYER_SUBMERGED_MINING_SPEED = AttributeImpl.REGISTRY.Get("minecraft:player.submerged_mining_speed");

	public 	static 	readonly IAttribute PLAYER_SWEEPING_DAMAGE_RATIO = AttributeImpl.REGISTRY.Get("minecraft:player.sweeping_damage_ratio");

	public 	static 	readonly IAttribute GENERIC_WATER_MOVEMENT_EFFICIENCY = AttributeImpl.REGISTRY.Get("minecraft:generic.water_movement_efficiency");

	}
}
