namespace Server.Attribute
{
	// This file was autogenerated by a script. Do not modify this file manually.
	public static class Attributes
	{
	public 	static 	readonly IAttribute Generic_armor = AttributeImpl.REGISTRY.Get("minecraft:generic.armor");

	public 	static 	readonly IAttribute Generic_armorToughness = AttributeImpl.REGISTRY.Get("minecraft:generic.armor_toughness");

	public 	static 	readonly IAttribute Generic_attackDamage = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_damage");

	public 	static 	readonly IAttribute Generic_attackKnockback = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_knockback");

	public 	static 	readonly IAttribute Generic_attackSpeed = AttributeImpl.REGISTRY.Get("minecraft:generic.attack_speed");

	public 	static 	readonly IAttribute Player_blockBreakSpeed = AttributeImpl.REGISTRY.Get("minecraft:player.block_break_speed");

	public 	static 	readonly IAttribute Player_blockInteractionRange = AttributeImpl.REGISTRY.Get("minecraft:player.block_interaction_range");

	public 	static 	readonly IAttribute Generic_burningTime = AttributeImpl.REGISTRY.Get("minecraft:generic.burning_time");

	public 	static 	readonly IAttribute Generic_explosionKnockbackResistance = AttributeImpl.REGISTRY.Get("minecraft:generic.explosion_knockback_resistance");

	public 	static 	readonly IAttribute Player_entityInteractionRange = AttributeImpl.REGISTRY.Get("minecraft:player.entity_interaction_range");

	public 	static 	readonly IAttribute Generic_fallDamageMultiplier = AttributeImpl.REGISTRY.Get("minecraft:generic.fall_damage_multiplier");

	public 	static 	readonly IAttribute Generic_flyingSpeed = AttributeImpl.REGISTRY.Get("minecraft:generic.flying_speed");

	public 	static 	readonly IAttribute Generic_followRange = AttributeImpl.REGISTRY.Get("minecraft:generic.follow_range");

	public 	static 	readonly IAttribute Generic_gravity = AttributeImpl.REGISTRY.Get("minecraft:generic.gravity");

	public 	static 	readonly IAttribute Generic_jumpStrength = AttributeImpl.REGISTRY.Get("minecraft:generic.jump_strength");

	public 	static 	readonly IAttribute Generic_knockbackResistance = AttributeImpl.REGISTRY.Get("minecraft:generic.knockback_resistance");

	public 	static 	readonly IAttribute Generic_luck = AttributeImpl.REGISTRY.Get("minecraft:generic.luck");

	public 	static 	readonly IAttribute Generic_maxAbsorption = AttributeImpl.REGISTRY.Get("minecraft:generic.max_absorption");

	public 	static 	readonly IAttribute Generic_maxHealth = AttributeImpl.REGISTRY.Get("minecraft:generic.max_health");

	public 	static 	readonly IAttribute Player_miningEfficiency = AttributeImpl.REGISTRY.Get("minecraft:player.mining_efficiency");

	public 	static 	readonly IAttribute Generic_movementEfficiency = AttributeImpl.REGISTRY.Get("minecraft:generic.movement_efficiency");

	public 	static 	readonly IAttribute Generic_movementSpeed = AttributeImpl.REGISTRY.Get("minecraft:generic.movement_speed");

	public 	static 	readonly IAttribute Generic_oxygenBonus = AttributeImpl.REGISTRY.Get("minecraft:generic.oxygen_bonus");

	public 	static 	readonly IAttribute Generic_safeFallDistance = AttributeImpl.REGISTRY.Get("minecraft:generic.safe_fall_distance");

	public 	static 	readonly IAttribute Generic_scale = AttributeImpl.REGISTRY.Get("minecraft:generic.scale");

	public 	static 	readonly IAttribute Player_sneakingSpeed = AttributeImpl.REGISTRY.Get("minecraft:player.sneaking_speed");

	public 	static 	readonly IAttribute Zombie_spawnReinforcements = AttributeImpl.REGISTRY.Get("minecraft:zombie.spawn_reinforcements");

	public 	static 	readonly IAttribute Generic_stepHeight = AttributeImpl.REGISTRY.Get("minecraft:generic.step_height");

	public 	static 	readonly IAttribute Player_submergedMiningSpeed = AttributeImpl.REGISTRY.Get("minecraft:player.submerged_mining_speed");

	public 	static 	readonly IAttribute Player_sweepingDamageRatio = AttributeImpl.REGISTRY.Get("minecraft:player.sweeping_damage_ratio");

	public 	static 	readonly IAttribute Generic_waterMovementEfficiency = AttributeImpl.REGISTRY.Get("minecraft:generic.water_movement_efficiency");

	}
}
