class Stringified:
    def as_str(self):
        raise NotImplementedError("to_string method must be implemented in child class.")


# enum modifiers
class Modifier:
    PUBLIC = "public"
    PRIVATE = "private"
    PROTECTED = "protected"
    INTERNAL = "internal"
    STATIC = "static"
    READONLY = "readonly"


class Namespace:
    # contains a list of classes
    def __init__(self, namespace_name):
        self.namespace_name = namespace_name
        self.classes = list()

    def add_class(self, class_obj):
        self.classes.append(class_obj)


class ModifierBound:
    def __init__(self):
        self.modifiers = list()

    def add_modifier(self, modifier):
        self.modifiers.append(modifier)


class Method(ModifierBound):
    def __init__(self):
        super().__init__()
        self.return_type = ""
        self.method_name = ""
        self.parameters = list()
        self.body = ""

    def set_return_type(self, return_type):
        self.return_type = return_type

    def set_name(self, method_name):
        self.method_name = method_name

    def set_body(self, body):
        self.body = body


class Field(ModifierBound, Stringified):
    def __init__(self):
        super().__init__()
        self.getter = False
        self.setter = False
        self.field_type = ""
        self.field_name = ""
        self.field_value = ""

    def as_str(self):
        return f"{self.field_name} = {self.field_value}"

    def set_field_value(self, field_value):
        self.field_value = field_value

    def set_field_type(self, field_type):
        self.field_type = field_type

    def set_field_name(self, field_name):
        self.field_name = field_name

    def set_getter(self, getter):
        self.getter = getter

    def set_setter(self, setter):
        self.setter = setter


class CsClass(ModifierBound, Stringified):
    def __init__(self, class_name):
        super().__init__()
        self.static_method_bodies = list() # list of strings
        self.class_name = class_name
        self.methods = list()
        self.fields = list()

    def add_static_method_body(self, static_method_body):
        self.static_method_bodies.append(static_method_body)

    def add_field(self, field_obj):
        self.fields.append(field_obj)


class CsFile:

    def __init__(self, file_path):
        self.file_path = file_path
        self.namespaces = list()

    def add_namespace(self, namespace_obj):
        self.namespaces.append(namespace_obj)

    def write_to_file(self):
        with open(self.file_path, "w") as file:
            for namespace in self.namespaces:
                file.write(f"namespace {namespace.namespace_name}\n")
                file.write("{\n")
                for class_obj in namespace.classes:
                    file.write("\t// This file was autogenerated by a script. Do not modify this file manually.\n")
                    file.write(f"\tpublic static class {class_obj.class_name}\n")
                    file.write("\t{\n")
                    for field in class_obj.fields:
                        for modifier in field.modifiers:
                            file.write(f"\t{modifier} ")
                        file.write(f"{field.field_type} {field.field_name}")
                        if field.setter or field.getter:
                            if field.getter:
                                file.write(" { get; }")
                            if field.setter:
                                file.write(" { set; }")
                            if field.field_value:
                                file.write(f" = {field.field_value}")
                        else:
                            file.write(f" = {field.field_value}")
                        file.write(";\n")
                        file.write("\n")
                    for method in class_obj.methods:
                        for modifier in method.modifiers:
                            file.write(f"\t{modifier} ")
                        file.write(f"{method.return_type} {method.method_name}(")
                        i = 0
                        for parameter in method.parameters:
                            file.write(f"{parameter}")
                            if i < len(method.parameters) - 1:
                                file.write(", ")
                            i += 1
                        file.write(")\n")
                        file.write("\t\t{\n")
                        file.write(f"\t\t\t{method.body}\n")
                        file.write("\t\t}\n")
                    file.write("\t}\n")
                file.write("}\n")
